import { AuthUserProvider } from '../firebase/auth'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Swift Cart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=' bg-swiftcart-light'>
        <AuthUserProvider>
          {children}
        </AuthUserProvider>
      </body>
    </html>
  )
}